BEGIN;

CREATE TABLE IF NOT EXISTS brokers (
    code VARCHAR(2) NOT NULL PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);

INSERT INTO brokers (code, name) VALUES
('AD', 'OSO Sekuritas Indonesia'),
('AF', 'Harita Kencana Sekuritas'),
('AG', 'Kiwoom Sekuritas Indonesia'),
('AH', 'Shinhan Sekuritas Indonesia'),
('AI', 'UOB Kay Hian Sekuritas'),
('AK', 'UBS Sekuritas Indonesia'),
('AN', 'Wanteg Sekuritas'),
('AO', 'Erdikha Elit Sekuritas'),
('AP', 'Pacific Sekuritas Indonesia'),
('AR', 'Binaartha Sekuritas'),
('AT', 'Phintraco Sekuritas'),
('AZ', 'Sucor Sekuritas'),
('BB', 'Verdhana Sekuritas Indonesia'),
('BF', 'Inti Fikasa Sekuritas'),
('BK', 'J.P. Morgan Sekuritas Indonesia'),
('BQ', 'Korea Investment and Sekuritas Indonesia'),
('BR', 'Trust Sekuritas'),
('BS', 'Equity Sekuritas Indonesia'),
('BZ', 'BATAVIA PROSPERINDO SEKURITAS'),
('CC', 'Mandiri Sekuritas'),
('CD', 'Mega Capital Sekuritas'),
('CG', 'CITIGROUP SEKURITAS INDONESIA'),
('CP', 'KB Valbury Sekuritas'),
('CS', 'Credit Suisse Sekuritas Indonesia'),
('DD', 'Makindo Sekuritas'),
('DH', 'Sinarmas Sekuritas'),
('DM', 'Masindo Artha Sekuritas'),
('DP', 'DBS Vickers Sekuritas Indonesia'),
('DR', 'RHB Sekuritas Indonesia'),
('DU', 'KAF Sekuritas Indonesia'),
('DX', 'Bahana Sekuritas'),
('EL', 'Evergreen Sekuritas Indonesia'),
('EP', 'MNC Sekuritas'),
('ES', 'Ekokapital Sekuritas'),
('FO', 'Forte Global Sekuritas'),
('FS', 'Yuanta Sekuritas Indonesia'),
('FZ', 'Waterfront Sekuritas Indonesia'),
('GA', 'BNC Sekuritas Indonesia'),
('GI', 'Webull Sekuritas Indonesia'),
('GR', 'Panin Sekuritas Tbk.'),
('GW', 'HSBC Sekuritas Indonesia'),
('HD', 'KGI Sekuritas Indonesia'),
('HP', 'Henan Putihrai Sekuritas'),
('IC', 'Integrity Capital Sekuritas'),
('ID', 'Anugerah Sekuritas Indonesia'),
('IF', 'Samuel Sekuritas Indonesia'),
('IH', 'Indo Harvest Sekuritas'),
('II', 'Danatama Makmur Sekuritas'),
('IN', 'Investindo Nusantara Sekuritas'),
('IP', 'Yugen Bertumbuh Sekuritas'),
('IT', 'Inti Teladan Sekuritas'),
('IU', 'Indo Capital Sekuritas'),
('JB', 'Bjb Sekuritas'),
('KI', 'Ciptadana Sekuritas Asia'),
('KK', 'Phillip Sekuritas Indonesia'),
('KS', 'Kresna Sekuritas'),
('KZ', 'CLSA Sekuritas Indonesia'),
('LG', 'Trimegah Sekuritas Indonesia Tbk.'),
('LH', 'Royal Investium Sekuritas'),
('LS', 'Reliance Sekuritas Indonesia Tbk.'),
('MG', 'Semesta Indovest Sekuritas'),
('MI', 'Victoria Sekuritas Indonesia'),
('MK', 'Ekuator Swarna Sekuritas'),
('MS', 'MORGAN STANLEY SEKURITAS INDONESIA'),
('MU', 'Minna Padi Investama Sekuritas'),
('NI', 'BNI Sekuritas'),
('OD', 'BRI Danareksa Sekuritas'),
('OK', 'Net Sekuritas'),
('PC', 'FAC Sekuritas Indonesia'),
('PD', 'Indo Premier Sekuritas'),
('PF', 'Danasakti Sekuritas Indonesia'),
('PG', 'Panca Global Sekuritas'),
('PI', 'Magenta Kapital Sekuritas Indonesia'),
('PO', 'Pilarmas Investindo Sekuritas'),
('PP', 'Aldiracita Sekuritas Indonesia'),
('PS', 'Paramitra Alfa Sekuritas'),
('QA', 'Tuntun Sekuritas Indonesia'),
('RB', 'Ina Sekuritas Indonesia'),
('RF', 'Buana Capital Sekuritas'),
('RG', 'Profindo Sekuritas Indonesia'),
('RO', 'Pluang Maju Sekuritas'),
('RS', 'Yulie Sekuritas Indonesia Tbk.'),
('RX', 'Macquarie Sekuritas Indonesia'),
('SA', 'Elit Sukses Sekuritas'),
('SC', 'IMG Sekuritas'),
('SF', 'Surya Fajar Sekuritas'),
('SH', 'Artha Sekuritas Indonesia'),
('SQ', 'BCA Sekuritas'),
('SS', 'Supra Sekuritas Indonesia'),
('TF', 'Universal Broker Indonesia Sekuritas'),
('TP', 'OCBC Sekuritas Indonesia'),
('TS', 'Dwidana Sakti Sekuritas'),
('TX', 'DHANAWIBAWA SEKURITAS INDONESIA'),
('XA', 'NH Korindo Sekuritas Indonesia'),
('XC', 'Ajaib Sekuritas Asia'),
('XL', 'Stockbit Sekuritas Digital'),
('YB', 'Yakin Bertumbuh Sekuritas'),
('YJ', 'Lotus Andalan Sekuritas'),
('YO', 'Amantara Sekuritas Indonesia'),
('YP', 'Mirae Asset Sekuritas Indonesia'),
('YU', 'CGS International Sekuritas Indonesia'),
('ZP', 'Maybank Sekuritas Indonesia'),
('ZR', 'Bumiputera Sekuritas');

ALTER TABLE brokers
ADD COLUMN IF NOT EXISTS
previous_names TEXT[] DEFAULT '{}';

COMMIT;